### ISSUE TITLE
`grant_type` is invalid

### ISSUE THREAD

**Issue by martijndierckx** [Domochip/gardena2mqtt#13]
I'm getting an error when trying to connect to the API:
Any ideas on what it could be?

```
11:26:37: ===== gardena2mqtt v1.0.2 =====
11:26:37: ===== Prepare MQTT Client =====
11:26:37: ===== Prepare SmartSystem Client =====
11:26:37:  - create
11:26:37:  - authenticate
Traceback (most recent call last):
  File "/app/gardena2mqtt.py", line 210, in <module>
    smart_system.authenticate()
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 115, in authenticate
    self.token = self.oauth_session.fetch_token(
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 429, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 432, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 402, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.UnauthorizedClientError: (unauthorized_client) Unauthorized client: `grant_type` is invalid
```

**Comment by Domochip** [comment]
Hey, sorry for the late reply 😄

I've adjusted the code for the new authentication and asynchronous methodology.

The new version is now available as "domochip/gardena2mqtt:latest-dev"
It would be great if you can test it before I release.

thanks
