### ISSUE TITLE
TypeError: '<=' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by bjornta** [Domochip/gardena2mqtt#2]
When trying to start the docker instance I get the following error:

07:59:13: ===== Connection To MQTT Broker =====
Traceback (most recent call last):
  File "/app/gardena2mqtt.py", line 226, in <module>
    mqttclient.connect(mqtthost, mqttport)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 939, in connect
    self.connect_async(host, port, keepalive,
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1006, in connect_async
    if port <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'

The credentials are correct as well as the hostname of the MQTT-server.

**Comment by bjornta** [comment]
Left out the following from docker startup, and it works:

    -e PORT=1883 \
    -e PREFIX=gardena2mqtt \
    -e CLIENTID=gardena2mqttclid \
